name: Deno CI

on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repo
       uses: actions/checkout@v2

     - name: Setup Deno
       uses: denoland/setup-deno@v1
       with:
         deno-version: v1.x

     - name: Check
       run: deno task check
